/**
 * This module exports an object containing various programming languages.
 * Each language includes its name and the corresponding key.
 */

export const languages = {
    rust: "Rust",
    c: "C",
    "c++": "C++",
    "c#": "C#",
    clojure: "Clojure",
    crystal: "Crystal",
    css: "CSS",
    diff: "Diff",
    dockerfile: "Docker",
    elm: "Elm",
    elixir: "Elixir",
    erlang: "Erlang",
    graphql: "GraphQL",
    go: "Go",
    haskell: "Haskell",
    html: "HTML",
    java: "Java",
    javascript: "JavaScript/JSX",
    json: "JSON",
    kotlin: "Kotlin",
    lisp: "Lisp",
    lua: "Lua",
    markdown: "Markdown",
    matlab: "MATLAB/Octave",
    pascal: "Pascal",
    plaintext: "Plaintext",
    powershell: "Powershell",
    objectivec: "Objective C",
    php: "PHP",
    python: "Python",
    ruby: "Ruby",
    bash: "Bash",
    scala: "Scala",
    scss: "SCSS",
    sql: "SQL",
    swift: "Swift",
    toml: "TOML",
    typescript: "TypeScript/TSX",
    xml: "XML",
    yaml: "YAML",
};
